# This works, the image size is 5.4 GB
FROM rust:latest

ENV DATABASE_URL=postgresql://localhost:5432/leetcode
ENV PORT=8080

WORKDIR /app
COPY . .

RUN rustup default nightly
RUN cargo build

CMD ["cargo", "run"]